# Clippy配置

# 最大认知复杂度
cognitive-complexity-threshold = 30

# 枚举变体最大数量
enum-variant-size-threshold = 200

# 函数参数最大数量
too-many-arguments-threshold = 7

# 函数行数最大值
too-many-lines-threshold = 100

# 类型复杂度阈值
type-complexity-threshold = 250

# 单个表达式的最大嵌套
excessive-nesting-threshold = 5

# 栈分配大小警告阈值
stack-size-threshold = 512000
