# Rust代码格式化配置

# 基础配置
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# 导入
reorder_imports = true
reorder_modules = true

# 其他
use_field_init_shorthand = true
use_try_shorthand = true
