name: build-binaries

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux-x64
            binary: claude-code-statusline-pro
            artifact: linux-x64
          - os: macos-13
            target: x86_64-apple-darwin
            platform: darwin-x64
            binary: claude-code-statusline-pro
            artifact: darwin-x64
          - os: macos-14
            target: aarch64-apple-darwin
            platform: darwin-arm64
            binary: claude-code-statusline-pro
            artifact: darwin-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: win32-x64
            binary: claude-code-statusline-pro.exe
            artifact: win32-x64

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Collect artifact
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/${{ matrix.binary }} artifacts/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: artifacts/${{ matrix.binary }}

  assemble-npm:
    name: assemble npm package
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: dist/artifacts

      - name: Arrange binaries for npm package
        run: |
          set -euo pipefail
          mkdir -p npm/ccstatus/binaries/darwin-arm64 \
                   npm/ccstatus/binaries/darwin-x64 \
                   npm/ccstatus/binaries/linux-x64 \
                   npm/ccstatus/binaries/win32-x64

          cp dist/artifacts/darwin-arm64/claude-code-statusline-pro npm/ccstatus/binaries/darwin-arm64/ccstatus || true
          cp dist/artifacts/darwin-x64/claude-code-statusline-pro npm/ccstatus/binaries/darwin-x64/ccstatus || true
          cp dist/artifacts/linux-x64/claude-code-statusline-pro npm/ccstatus/binaries/linux-x64/ccstatus || true
          cp dist/artifacts/win32-x64/claude-code-statusline-pro.exe npm/ccstatus/binaries/win32-x64/ccstatus.exe || true

          chmod +x npm/ccstatus/binaries/darwin-arm64/ccstatus 2>/dev/null || true
          chmod +x npm/ccstatus/binaries/darwin-x64/ccstatus 2>/dev/null || true
          chmod +x npm/ccstatus/binaries/linux-x64/ccstatus 2>/dev/null || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Pack ccstatus
        run: npm --prefix npm/ccstatus pack

      - name: Pack legacy package
        run: npm --prefix npm/claude-code-statusline-pro pack

      - name: Upload npm tarballs
        uses: actions/upload-artifact@v4
        with:
          name: npm-packages
          path: |
            npm/ccstatus/*.tgz
            npm/claude-code-statusline-pro/*.tgz
