name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            platform: linux-x64
            binary: claude-code-statusline-pro
            artifact: linux-x64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            platform: linux-arm64
            binary: claude-code-statusline-pro
            artifact: linux-arm64
            setup: install-linux-arm-toolchain
          - os: macos-13
            target: x86_64-apple-darwin
            platform: macos-x64
            binary: claude-code-statusline-pro
            artifact: macos-x64
          - os: macos-14
            target: aarch64-apple-darwin
            platform: macos-arm64
            binary: claude-code-statusline-pro
            artifact: macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows-x64
            binary: claude-code-statusline-pro.exe
            artifact: windows-x64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            platform: windows-arm64
            binary: claude-code-statusline-pro.exe
            artifact: windows-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install cross toolchain
        if: matrix.setup == 'install-linux-arm-toolchain'
        run: |
          sudo dpkg --add-architecture arm64 || true

          # 备份并完全替换 ubuntu.sources 文件（Ubuntu 24.04 DEB822 格式）
          if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then
            sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources.bak
            cat <<'EOF' | sudo tee /etc/apt/sources.list.d/ubuntu.sources
          Types: deb
          URIs: http://archive.ubuntu.com/ubuntu
          Suites: noble noble-updates noble-backports
          Components: main restricted universe multiverse
          Architectures: amd64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

          Types: deb
          URIs: http://security.ubuntu.com/ubuntu
          Suites: noble-security
          Components: main restricted universe multiverse
          Architectures: amd64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
          EOF
          fi

          # 修改传统的 sources.list 文件（如果存在）
          if [ -f /etc/apt/sources.list ]; then
            sudo sed -i 's/^deb /deb [arch=amd64] /' /etc/apt/sources.list
            sudo sed -i 's/^deb-src /deb-src [arch=amd64] /' /etc/apt/sources.list
          fi

          # 为 arm64 添加独立的 ports 源
          cat <<'EOF' | sudo tee /etc/apt/sources.list.d/ubuntu-ports.sources
          Types: deb
          URIs: http://ports.ubuntu.com/ubuntu-ports
          Suites: noble noble-updates noble-security noble-backports
          Components: main restricted universe multiverse
          Architectures: arm64
          Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
          EOF

          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libssl-dev:arm64 \
            pkg-config

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build ${{ matrix.target }}
        shell: bash
        run: |
          if [[ "${{ matrix.platform }}" == "linux-arm64" ]]; then
            export PKG_CONFIG_ALLOW_CROSS=1
            export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
            export OPENSSL_DIR=/usr
            export OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
            export OPENSSL_INCLUDE_DIR=/usr/include/aarch64-linux-gnu
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            export CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc
            export AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc-ar
          fi
          cargo build --release --target ${{ matrix.target }}

      - name: Collect artifact
        run: |
          mkdir -p artifacts
          cp target/${{ matrix.target }}/release/${{ matrix.binary }} artifacts/
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: artifacts/${{ matrix.binary }}

  assemble-npm:
    name: assemble npm package
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: npm-release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: dist/artifacts

      - name: Arrange binaries for npm packages
        run: |
          set -euo pipefail

          declare -a PLATFORMS=(
            "macos-arm64:claude-code-statusline-pro:ccstatus"
            "macos-x64:claude-code-statusline-pro:ccstatus"
            "linux-x64:claude-code-statusline-pro:ccstatus"
            "linux-arm64:claude-code-statusline-pro:ccstatus"
            "windows-x64:claude-code-statusline-pro.exe:ccstatus.exe"
            "windows-arm64:claude-code-statusline-pro.exe:ccstatus.exe"
          )

          for entry in "${PLATFORMS[@]}"; do
            IFS=":" read -r platform sourceBinary destBinary <<<"$entry"
            pkg_dir="npm/platforms/ccstatus-${platform}/bin"
            mkdir -p "${pkg_dir}"

            artifact_path="dist/artifacts/${platform}/${sourceBinary}"
            if [ -f "${artifact_path}" ]; then
              cp "${artifact_path}" "${pkg_dir}/${destBinary}"
              if [[ "${destBinary}" != *.exe ]]; then
                chmod +x "${pkg_dir}/${destBinary}"
              fi
              rm -f "${pkg_dir}/.gitkeep"
            else
              echo "No artifact found for ${platform}, leaving placeholder."
            fi
          done

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Pack platform packages
        run: |
          set -euo pipefail
          packages=(
            ccstatus-macos-arm64
            ccstatus-macos-x64
            ccstatus-linux-x64
            ccstatus-linux-arm64
            ccstatus-windows-x64
            ccstatus-windows-arm64
          )
          for pkg in "${packages[@]}"; do
            pkg_dir="npm/platforms/${pkg}"
            rm -f "${pkg_dir}"/*.tgz
            (cd "${pkg_dir}" && npm pack)
          done

      - name: Pack ccstatus
        run: |
          set -euo pipefail
          rm -f npm/ccstatus/*.tgz
          (cd npm/ccstatus && npm pack)

      - name: Pack legacy package
        run: |
          set -euo pipefail
          rm -f npm/claude-code-statusline-pro/*.tgz
          (cd npm/claude-code-statusline-pro && npm pack)

      - name: Read release version
        id: release-version
        run: |
          set -euo pipefail
          VERSION=$(node -p "require('./npm/ccstatus/package.json').version")
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Smoke test assembled packages (linux-x64)
        run: |
          set -euo pipefail
          PLATFORM_TARBALL=$(ls npm/platforms/ccstatus-linux-x64/*.tgz)
          MAIN_TARBALL=$(ls npm/ccstatus/*.tgz)
          LEGACY_TARBALL=$(ls npm/claude-code-statusline-pro/*.tgz)

          TMP_DIR=$(mktemp -d)
          trap 'rm -rf "$TMP_DIR"' EXIT

          npm install --prefix "$TMP_DIR" --no-save "$PLATFORM_TARBALL"
          npm install --prefix "$TMP_DIR" --no-save "$MAIN_TARBALL"
          npm install --prefix "$TMP_DIR" --no-save "$LEGACY_TARBALL"

          NODE_PATH="$TMP_DIR/node_modules" node "$TMP_DIR/node_modules/claude-code-statusline-pro/index.js" --version
          NODE_PATH="$TMP_DIR/node_modules" node "$TMP_DIR/node_modules/ccstatus/index.js" --help >/dev/null

      - name: Ensure npm versions are unpublished
        env:
          VERSION: ${{ steps.release-version.outputs.version }}
        run: |
          set -euo pipefail
          packages=(
            ccstatus
            claude-code-statusline-pro
            @wangnov/ccstatus-linux-x64
            @wangnov/ccstatus-linux-arm64
            @wangnov/ccstatus-macos-x64
            @wangnov/ccstatus-macos-arm64
            @wangnov/ccstatus-windows-x64
            @wangnov/ccstatus-windows-arm64
          )
          for pkg in "${packages[@]}"; do
            if npm view "${pkg}@${VERSION}" > /dev/null 2>&1; then
              echo "::error::${pkg}@${VERSION} already exists on npm"
              exit 1
            fi
          done

      - name: Publish npm packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -euo pipefail
          npm config set //registry.npmjs.org/:_authToken "${NODE_AUTH_TOKEN}"

          for file in npm/platforms/*/*.tgz; do
            npm publish "$file" --access public
          done

          npm publish "$(ls npm/ccstatus/*.tgz)" --access public
          npm publish "$(ls npm/claude-code-statusline-pro/*.tgz)" --access public

      - name: Upload npm tarballs
        uses: actions/upload-artifact@v4
        with:
          name: npm-packages
          path: |
            npm/platforms/*/*.tgz
            npm/ccstatus/*.tgz
            npm/claude-code-statusline-pro/*.tgz
